alpaca/common/rest.py, alpaca/data/historical.py, alpaca/data/live.py
This allows for overriding with str values if someone needs to use a proxy/local mock servers (I'd like to add this later for integration tests but is also useful in general for users)
=> Add URL overriding to clients

alpaca/common/enums.py, alpaca/common/models/__init__.py, alpaca/common/models/trading.py, alpaca/data/enums.py, tests/common/factories/__init__.py, tests/common/factories/trading.py, tests/common/test_common_models.py
* Adds `Asset` Model
* Adds `AssetClass`, `AssetStatus` and `AssetExchange` Enums. `AssetExchange` was created because the existing`Exchange` enum lists specific exchange datafeeds whereas the exchange field in `Asset` more generally lists which exchange the asset is related to. There's also a lot of overlap in terms of which exchanges they're referring to, I thought it would be cleaner to create a new `AssetExchange` enum to avoid any headache of duplicate exchanges within the same enum.
* Also added a small change to move the Data API enums to inherit from `str`.
=> Adds Asset Model

alpaca/broker/client.py, alpaca/broker/models/__init__.py, alpaca/broker/models/trading.py, tests/broker/broker_client/test_trading_routes.py, tests/broker/factories/__init__.py, tests/broker/factories/trading.py
Resolves #37
Resolves #38 
Couple notes:
* This is branched off `ryan/common-trading-models` so diffs look messy until that is merged.
* For `close_all_positions_for_account` we have the `cancel_orders: bool` parameter. I am not sure if we want to wrap this in a pydantic model like we do for other request options to future proof if there may be more options for this this route in the future?
* We currently are relying on `datetime.date` default string cast for `GetPortfolioHistoryRequest.date_end` when converting to request fields. This works as is since Alpaca expects `YYY-MM-DD` format, but let me know if we should have a more robust conversion for dates/datetimes.
=> Broker API: Trading Routes

docs/index.rst
Corrects the URLs for the Shield Badges on the homepage so that the info displayed is linked to the correct project/repo
=> Fix Shield Badges on homepage

alpaca/trading/models.py
Fixes [this issue](https://github.com/alpacahq/alpaca-py/issues/161).
The trading client's `get_all_assets` method does not return minimum_order_size for cryptocurrencies because there were some parameters not implemented. Adding these into the `Asset` model solves the problem.
Example of new asset response:
```
id=UUID('c9b6f16b-e88d-439f-bb0b-acecccab3d10') asset_class=<AssetClass.CRYPTO: 'crypto'> exchange=<AssetExchange.FTXU: 'FTXU'> symbol='BCH/BTC' name='Bitcoin Cash / Bitcoin ' status=<AssetStatus.ACTIVE: 'active'> tradable=True marginable=False shortable=False easy_to_borrow=False fractionable=True min_order_size=0.001 min_trade_increment=0.001 price_increment=1e-06
```
=> Fix: Adding extra optional params to Asset model to accommodate cryptocurrencies

alpaca/trading/enums.py
This order status is not documented [here](https://alpaca.markets/docs/api-references/broker-api/trading/orders/#order-status) but the back-end sends it in some rare cases. I've added it into C# SDK months ago for unblocking clients' bracket order placement logic. This PR should solve issue #153 completely.
=> Added new order status `held`

README.md
If you pass in the string as presented in the description, an error will be thrown. Passing in a formatted datetime will not throw an error, so I have changed the string to reflect that.
=> Change string to datetime

alpaca/broker/client.py, alpaca/trading/client.py, tests/trading/trading_client/test_order_routes.py
Fixes issue #199 - the correct URL used for both trading and broker clients and unit test updated according to documentation.
=> Fixed issue with the `get_order_for_account_by_client_id` functions

alpaca/broker/client.py, alpaca/trading/client.py, alpaca/trading/models.py, docs/api_reference/broker/corporate-actions.rst, docs/api_reference/trading/corporate-actions.rst, tests/trading/trading_client/test_corporate_announcements.py
This PR fixes https://github.com/alpacahq/alpaca-py/issues/172 
The parameter ex_date must be optional in the CorporateActionAnnouncement base model since it's not present in all responses from the API. Also fixed some typos.
=> fix: https://github.com/alpacahq/alpaca-py/issues/172

pyproject.toml
Good day 👋
In order to use your type hinting, type checkers like mypy require you to be [pep 561](https://peps.python.org/pep-0561/) compliant.
=> feat: support type checking

alpaca/broker/requests.py
Attributes of requests to /v1/events/trades are optional (https://alpaca.markets/docs/api-references/broker-api/events/#request), but the Python client raises an error if some but not all attributes are provided.
=> Update GetEventsRequest to match Broker API docs 

alpaca/data/__init__.py
Removing the live module from the websockets init fixes the circular import problem when using the raw websockets modules and allows more flexibility from the end user. The live module is a higher level implementation of websockets BaseStream and really shouldn't be included.
Removed:  from .live import *   from __init__.py
=> Fix for circular import error on websockets.py

alpaca/common/rest.py, alpaca/data/historical/stock.py
My company is using our Broker API key and secret to access the Market Data API as mentioned in the docs [here](https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/).
However, this requires us to use basic authorisation headers, i.e. `Authorization: Basic <base64_encoded_key_and_secret>` with our API key and secret.
Ideally, it would be great to just pass our Broker API key and secret to use the `APCA-API-KEY-ID` / `APCA-API-SECRET-KEY` headers, passing `api_key` and `secret_key` to the `StockHistoricalDataClient` as per usual.
Perhaps there is a way to override the `_get_auth_headers` method for the `RESTClient`?
https://github.com/alpacahq/alpaca-py/blob/master/alpaca/common/rest.py#L148-L149
I've copied the alpaca-py package in our VCS and made the exact same …
=> Add support for basic authorization for `StockHistoricalDataClient` and `RESTClient`

README.md
The example for `CryptoBarsRequest` in `README.md` currently fails due to using a string instead of a `datetime` object. The [documentation](https://alpaca.markets/docs/python-sdk/market_data.html#retrieving-historical-bar-data) has a corrected example. This PR updates `README.md` to match the documentation.
=> documentation: fix README to have correct datetime type for CryptoBarsRequest

alpaca/broker/models/documents.py
Both the `id` and the `document_type` field of the `AccountDocument` object need to be optional. You cannot create a `AccountDocument` because no `id` exists before creation, and the is also returning `document_type=None` in a few cases for me.
This PR should fix both issues. Related and expands upon this PR: https://github.com/alpacahq/alpaca-py/pull/286/files
=> Fixing mandatory Acccount Document pydantic fields

alpaca/broker/enums.py
fixes an issue we got from running in production:
```
ValueError: 'social_security_number_verification' is not a valid DocumentType
```
=> adding ss number verification enum

alpaca/broker/models/documents.py
After trying https://github.com/alpacahq/alpaca-py/pull/304 we ran into an additional issue where the documents don't actually return content so pydantic is erroring on that:
```
*** pydantic.error_wrappers.ValidationError: 3 validation errors for ParsingModel[List[alpaca.broker.models.documents.AccountDocument]]
__root__ -> 1 -> content
field required (type=value_error.missing)
__root__ -> 2 -> content
field required (type=value_error.missing)
__root__ -> 3 -> content
field required (type=value_error.missing)
```
API response:
```
[{'content': '<truncating for security/privacy>',
'created_at': '2023-07-06T15:24:10.880969Z',
'document_sub_type': 'passport',
'document_type': <DocumentType.IDENTITY_VERIFICATION: 'identity_verification'>,
'id': '161b9f84-b86d-4233-a49b-1067aacf87a0'}, …
```
=> Marking content as optional as the api may return docuements without it

alpaca/trading/__init__.py
Fixes [this issue](https://github.com/alpacahq/alpaca-py/issues/147)
=> Fix: Add trading stream class import to init file

alpaca/trading/models.py
If corporate announcements in the timeframe specified in `trading_client.get_corporate_announcements` are missing either the `target_symbol` or `target_original_cusip` fields, the function will raise an error via Pydantic. 
To fix this I made these two fields optional in the `CorporateActionAnnouncement` class. This may not be what is wanted long-term since I assume corporate announcements are only useful if they contain at least the `target_symbol` field, but it is a necessary fix for now to make the api usable.
=> Fix #291 by making target_symbol, target_original_cusip optional in CorporateActionAnnouncement

alpaca/broker/requests.py
fixing an issue that prevented orders from being created because of how pydantic was being called
fixes #274 
```
❯ python
Python 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from alpaca.broker.requests import OrderRequest
>>> from alpaca.common.enums import SupportedCurrencies
>>> OrderRequest(symbol="AAPL", side="buy", type="limit", time_in_force="day", qty=1, currency=SupportedCurrencies.USD)
{   'client_order_id': None,
'commission': None,
'currency': <SupportedCurrencies.USD: 'USD'>,
'extended_hours': None,
'notional': None,
'order_class': None,
'qty': 1.0,
'side': <OrderSide.BUY: 'buy'>,
'stop_loss': None,
'symbol': 'AAPL',
'take_profit': None,
'time_in_force': …
```
=> fixes issue #274 - can this get a review???????????????????????????

.github/workflows/publish-pypi.yaml
Right now when we push to master a new commit, the workflow that publish the commit to PyPI fails because we publish the same tag since new tag is not created yet. So after this PR we will publish to PyPI only when a tag is created.
=> Fix Workflow: Publish PyPI only on tag push

alpaca/broker/enums.py
pydantic_core._pydantic_core.ValidationError: 1 validation error for TradeDocument
type
Input should be 'account_statement', 'trade_confirmation', 'trade_confirmation_json', 'tax_statement', 'tax_1099_b_details', 'tax_1099_b_form', 'tax_1099_div_details', 'tax_1099_div_form', 'tax_1099_int_details', 'tax_1099_int_form' or 'tax_w8' [type=enum, input_value='account_application', input_type=str]
=> adding the account application enum type

alpaca/trading/models.py
fixes https://github.com/alpacahq/alpaca-py/issues/371
Context:
- we have validation errors for TradeUpdate reported in #371 
Changes:
- fix TradeUpdate model to set None as default
How to check:
- you can use the below code in google colab
```
! pip install git+https://github.com/hiohiohio/alpaca-py.git@fix-trade-update-model
api_key=<YOUR API KEY>
secret_key=<YOUR SECRET>
paper = True
import nest_asyncio
nest_asyncio.apply()
from alpaca.trading.stream import TradingStream
cli = TradingStream(api_key, secret_key, paper=paper)
async def msg_handler(msg) -> None:
print(msg)
cli.subscribe_trade_updates(msg_handler)
cli.run()
```
=> fix: Fix TradeUpdate model for validation error

alpaca/data/requests.py
Fixed some docstrings - aligned the classes mentioned in-text with the parents appearing in the class definitions.
=> Requests: fixed "see also" parent classes in docstrings

alpaca/common/requests.py, tests/broker/broker_client/test_account_activities_routes.py, tests/data/test_historical_crypto_data.py, tests/data/test_historical_stock_data.py
Fixes https://github.com/alpacahq/alpaca-py/issues/236
Context:
- tradeclient.get_orders errors when datetime has timezone
- we would like to support timezone aware datetime as well as naive datetime
Changes:
- support timezone aware datetime
you can use below code to check in google colab
```
! pip install git+https://github.com/hiohiohio/alpaca-py.git@support-datetime-with-timezone
import datetime
from zoneinfo import ZoneInfo
from alpaca.trading.requests import GetOrdersRequest
from alpaca.trading.enums import QueryOrderStatus
from alpaca.trading.client import TradingClient
api_key=<YOUR API KEY>
secret_key=<YOUR SECRET KEY>
paper = True
client = TradingClient(api_key, secret_key, paper=paper)
nowUTC = datetime.datetime.now(datetime.timezone.utc)
req = …
```
=> fix: Support timezone aware datetime for get_orders()

alpaca/broker/enums.py
```
1 validation error for AccountDocument
document_type
Input should be 'identity_verification', 'address_verification', 'date_of_birth_verification', 'tax_id_verification', 'account_approval_letter', 'limited_trading_authorization', 'w8ben', 'social_security_number_verification' or '' [type=enum, input_value='cip_result', input_type=str]
```
=> adding cip result document type

alpaca/data/live/crypto.py
fixes #383 
Context:
- there is 404 error when subscribe crypto data feed
Changes:
- avoid using f-string for enum
Ref:
- log indicates that enum value is used for f-string replacement for this issue. `CryptoFeed.US` should be `us` in the very last line of the below.
```
>>> wss_client.run()
DEBUG:asyncio:Using selector: EpollSelector
INFO:alpaca.common.websocket:started data stream
INFO:alpaca.common.websocket:starting data websocket connection
DEBUG:websockets.client:= connection is CONNECTING
DEBUG:websockets.client:> GET /v1beta3/crypto/CryptoFeed.US HTTP/1.1
```
You can test this by
```bash
$ docker run -it --entrypoint bash python:3.12-slim
$ apt-get update && apt-get install git -y
$ pip install git+https://github.com/hiohiohio/alpaca-py.git@fix-stream-url-not-found
$ python3 …
```
=> fix: remove f-string for enum

.github/workflows/publish-pypi.yaml, alpaca/__init__.py, pyproject.toml
- use poetry-dynamic-versioning to specify release version of the alpaca-py package by git tag of `v0.0.0`
=> feat: Use poetry-dynamic-versioning

.github/workflows/publish-pypi.yaml, pyproject.toml
Context:
- introduced poetry-dynamic-versioning in https://github.com/alpacahq/alpaca-py/pull/390
- however, it causes an error when installing the poetry-dynamic-versioning package as pipx does not support installing multiple packages
```
pipx install poetry poetry-dynamic-versioning
shell: /usr/bin/bash -e {0}
usage: pipx [-h] [--version]
{install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions}
...
pipx: error: unrecognized arguments: poetry-dynamic-versioning
Error: Process completed with exit code 2.
```
Changes:
- separate installing poetry-dynamic-versioning for poetry-publish
=> fix: Fix publish-pypi

alpaca/data/historical/stock.py, alpaca/data/historical/utils.py, alpaca/data/models/bars.py, alpaca/data/models/base.py, alpaca/data/models/quotes.py, alpaca/data/models/snapshots.py, alpaca/data/models/trades.py, tests/data/test_historical_stock_data.py
fixes https://github.com/alpacahq/alpaca-py/issues/317
Context:
- we currently cannot handle empty response when querying trades/quotes/snapshot/etc...
- this PR fixes unintended errors when handling empty response.
Changes:
- returning empty object/dict instead of raising an error when API returns empty data
=> fix: Fix handling empty market data

alpaca/trading/enums.py, alpaca/trading/models.py, tests/trading/trading_client/test_account_routes.py
Context:
- max_option_trading_level field is added into response of account configuration
Chages:
- add max_option_trading_level field into account configuration model
=> feat: Adjust account configuration

alpaca/common/utils.py, alpaca/trading/client.py, docs/api_reference/trading/positions.rst, examples/options-trading-basic.ipynb, tests/trading/trading_client/test_position_routes.py
Context:
- A new API endpoint to exercise  an option contract (BETA) is introduced (https://docs.alpaca.markets/v1.1/reference/optionexercise)
- This PR support the API endpoint
Changes:
- add exercise_options_position
=> feat: add exercise_options_position

alpaca/data/historical/crypto.py, alpaca/data/historical/option.py, alpaca/data/historical/stock.py
Context:
- There is an issue of handling limit parameter due to recent change of marketdata api behaviour
- The API may return less than limit, even if there are more available data points in the requested interval
Changes:
- count total_items using actual number of response items
=> fix: Handle limit parameter

alpaca/trading/client.py, alpaca/trading/models.py, alpaca/trading/requests.py, examples/options-trading-basic.ipynb, tests/trading/trading_client/test_option_routes.py
Context:
- [get options contracts API endpoint](https://docs.alpaca.markets/reference/get-options-contracts) is updated with incompatible changes
-  request
- `underlying_symbol` parameter is removed and now `underlying_symbols` parameter (`optional` instead of required)
-  `page` parameter is removed is removed and now `page_token` parameter
- response
- `limit` and `page` are removed and now `next_page_token` field
Changes:
- update get_option_contracts
=> feat: Update get_option_contracts

README.md
Context:
- README.md is copied as pypi's [project description](https://pypi.org/project/alpaca-py/)
- therefore, the relative link to jupyter notebook becomes 404 link.
Changes:
- use URL instead of relative link
=> doc: Update link to jupyter notebook in README

alpaca/data/historical/option.py, alpaca/data/models/bars.py, alpaca/data/models/quotes.py, alpaca/data/models/trades.py, alpaca/data/requests.py, docs/api_reference/data/common.rst, docs/api_reference/data/common/requests.rst, docs/api_reference/data/crypto/requests.rst, docs/api_reference/data/option/historical.rst, docs/api_reference/data/option/requests.rst, docs/api_reference/data/stock/requests.rst, docs/api_reference/data_api.rst, examples/options-trading-basic.ipynb, tests/data/test_historical_option_data.py
Context:
- support newly added options market data endpoints
- [Historical bars](https://docs.alpaca.markets/reference/optionbars)
- [Exchange codes](https://docs.alpaca.markets/reference/optionmetaexchanges)
- [Historical trades](https://docs.alpaca.markets/reference/optiontrades)
Changes:
- added `get_option_bars()`
- added `get_option_exchange_codes()`
- added `get_option_trades()`
- updated docs for options market data
=> feat: Support options market data api (historical bars/trades and exchange codes)

alpaca/trading/client.py, alpaca/trading/models.py, tests/trading/trading_client/test_account_routes.py
Context:
- max_options_trading_level should be int instead of str
Changes:
- fix max_options_trading_level to use int instead of str
- fix set_account_configurations;
=> fix: use int for max_options_trading_level of AccountConfiguration

alpaca/trading/enums.py, alpaca/trading/requests.py, docs/api_reference/trading/enums.rst, tests/trading/trading_client/test_order_routes.py
- Accepting position intent in order request
- [Feature request](https://github.com/alpacahq/Alpaca-API/issues/85)
- trading enums are extended with a class called PositionIntent
- order request accept this as a new optional parameter
```py
BUY_TO_OPEN = "buy_to_open"
BUY_TO_CLOSE = "buy_to_close"
SELL_TO_OPEN = "sell_to_open"
SELL_TO_CLOSE = "sell_to_close"
```
=> feat: Support position intent in order requests

alpaca/trading/models.py, tests/broker/broker_client/test_trading_routes.py
Context:
- profit_loss_pct could be null values of array in API response of [Get Account Portfolio History](https://docs.alpaca.markets/reference/get-v1-trading-accounts-account_id-account-portfolio-history-1)
- current model raises validation error when receiving null values
- this PR fix the model definition
Changes:
- change profit_loss_pct to List[Optional[float]] in PortfolioHistory model
=> fix: Change profit_loss_pct to List[Optional[float]] in PortfolioHistory model

poetry.lock, pyproject.toml
- relax websockets version requirements
=> fix: Relax websockets version requirements

alpaca/trading/requests.py, tests/trading/trading_client/test_order_routes.py
Context:
- ReplaceOrderRequest ignores qty/limit_price/stop_price/trail if value is zero
- this may cause confusion
- this PR will add validation to ReplaceOrderRequest to let users know that those values should be greater than zero
Change:
- add validation to ReplaceOrderRequest
- apply `poetry run isort --profile black <file>`
=> fix: Add validation to ReplaceOrderRequest

alpaca/data/historical/option.py, alpaca/data/mappings.py, alpaca/data/models/snapshots.py, alpaca/data/requests.py, docs/api_reference/data/models.rst, tests/data/test_historical_option_data.py
- `get_option_snapshot` returns `OptionsSnapshot` instead of `Snapshot`
- `get_option_chain` returns `OptionsSnapshot` instead of `Snapshot`
- the [options snapshot](https://docs.alpaca.markets/reference/optionsnapshots) and [options chain](https://docs.alpaca.markets/reference/optionchain) API endpoints returns options greeks and implied volatility
- the options chain api endpoint accept new parameters to filter options contracts
- this PR support those changes of api endpoints
- introduce `OptionsSnapshot`
- support  `greeks` and "implied_volatility" of options snapshot
- support filter parameters of options chain api endpoint
- ref. https://docs.alpaca.markets/reference/optionchain
=> feat: Support changes of options snapshots and chain

alpaca/broker/enums.py
Context:
- we missed one JournalStatus `correct` in our enum
- this PR will fix the issue
- fixes https://github.com/alpacahq/alpaca-py/issues/447
- ref. https://docs.alpaca.markets/docs/funding-via-journals#journals-status
Changes:
- add correct into JournalStatus
=> fix: Add correct JournalStatus

alpaca/broker/client.py, alpaca/common/rest.py, tests/broker/broker_client/test_accounts_routes.py
Context:
- we have got `request body format is invalid` error when updating trade configuration for an account
- We should pass dict to json parameter instead of json_str
Changes:
- use model_dump() instead of model_dump_json() to pass dict instead of json string
=> fix: Fix update_trade_configuration_for_account()

alpaca/broker/requests.py
Context:
- transmitter info is required in some cases to process journal requests
Changes:
- transmitter info is added into BatchJournalRequestEntry
- add description into BatchJournalRequestEntry
=> feat: Add transmitter info into BatchJournalRequestEntry

alpaca/broker/client.py, tests/broker/broker_client/test_accounts_routes.py
Context:
- close_account was introduced and delete_account was deprecated
- https://docs.alpaca.markets/reference/post-v1-accounts-account_id-actions-close-1
Changes:
- add `BrokerClient.close_account()`
- set `BrokerClient.delete_account()` deprecated. Please use `BrokerClient.close_account()` instead
=> feat: Add BrokerClient.close_account

docs/index.rst
adds meta image to docs 
https://alpaca.markets/static/images/meta-image-alpaca-py.png
=> M1-372: alpaca-py meta image

alpaca/broker/models/accounts.py, tests/broker/broker_client/test_accounts_routes.py
Context:
- account has kyc_results in response
- https://docs.alpaca.markets/reference/getaccount
Changes:
- add kyc_results
=> feat: Add kyc_results into broker account

alpaca/data/models/bars.py, alpaca/data/models/base.py, alpaca/data/models/orderbooks.py, alpaca/data/models/quotes.py, alpaca/data/models/screener.py, alpaca/data/models/snapshots.py, alpaca/data/models/trades.py, alpaca/data/requests.py, docs/conf.py
Context:
- we have added `model_config = ConfigDict(protected_namespaces=tuple())` to avoid an error of sphinx
- `NameError: Field "model_fields" conflicts with member {} of protected namespace "model_".`
- found a workaround to avoid putting the member variable
Changes:
- import a module in conf.py to remove model_config
=> fix: Remove model_config for sphinx

alpaca/common/enums.py, alpaca/data/historical/crypto.py, alpaca/data/historical/option.py, alpaca/data/historical/stock.py
- Adds sandbox data endpoint support to the historical clients
- Adds `use_basic_auth` argument to the crypto historical client as it required for use with broker API credentials
- added `DATA_SANDBOX` to `BaseURL` enum
- added `sandbox` argument to historical clients. 
- added `use_basic_auth` argument to crypto historical client
- Updated docs to indicate `use_basic_auth` as to be True when using broker API credentials
=> feat: Add sandbox data support

alpaca/broker/enums.py
Hello,
On June 27th, 2024 at 8:47PM EST, we received this error from the Alpaca API:
```
APIError : {\"code\":40010001,\"message\":\"visa_type must be one of: [E1 E2 E3 F1 H1B TN1 O1 J1 L1 B1 B2 DACA G4 OTHER]\"}"}
```
We attempted to make a request to the Broker create an account endpoint and passed `VisaType.Other` as the input to the `Identity.visa_type` field.
We believe that it is because the API expects value `"OTHER"` not `"Other"`.
=> Change Visa_Type to match API expectations.

alpaca/trading/models.py, tests/trading/trading_client/test_corporate_announcements.py
Fixes https://github.com/alpacahq/alpaca-py/issues/366
Context:
- there are validation errors for get_corporate_announcements()
Changes:
- adjust type of `record_date` and `payable_date` to be nullable
=> fix: Fix get_corporate_announcements()

alpaca/broker/requests.py
Incompatible changes:
- `description` is removed from `CreateBatchJournalRequest` and `CreateReverseBatchJournalRequest`
Context:
- we missed transmitter info in ReverseBatchJournalRequestEntry
- description for batch journal request should be in each entry instead of header
Changes:
- add transmitter info into `ReverseBatchJournalRequestEntry`
- add `description` into `ReverseBatchJournalRequestEntry`
- remove `description` from `CreateBatchJournalRequest` and `CreateReverseBatchJournalRequest`
=> feat: Add transmitter info into ReverseBatchJournalRequestEntry

alpaca/trading/requests.py, tests/trading/trading_client/test_order_routes.py
fixes https://github.com/alpacahq/alpaca-py/issues/401
Context:
- limit_price is not required for oco limit order but  current validation of LimitOrderRequest requires
Changes:
- set limit_price optional for oco order
=> fix: Fix limit order request validation for oco

examples/stocks-trading-basic.ipynb
Fixes https://github.com/alpacahq/alpaca-py/issues/499
Context:
- To enable features recently added (i.e. fractional/options trading) for paper account, resetting the paper account is required.
- this process is only required for old paper accounts not for recent paper accounts/live accounts
Changes:
- add a comment to reset paper account when facing an error of `qty must be integer`
=> doc: Add a comment to reset paper account when qty must be integer

README.md, docs/getting_started.rst, docs/index.rst
Context:
- options trading in Alpaca is no longer beta
Changes:
- remove beta for options
=> doc: Remove beta for options

alpaca/broker/client.py, alpaca/broker/requests.py, alpaca/common/rest.py, alpaca/trading/requests.py, tests/broker/broker_client/test_trading_routes.py, tests/trading/trading_client/test_order_routes.py
Context:
- while reviewing rebalance API endpoints PR, noticed that `BrokerClient.cancel_orders_for_account()` raises validation error when receiving response due to mismatch of response object
Changes:
- remove CancelOrderResponse from broker side
- add `body` fields into CancelOrderResponse of trading
- fix type of delete in common/rest.py
=> fix: Fix BrokerClient.cancel_orders_for_account()

alpaca/data/live/crypto.py
A tiny fix to reduce false highlights about type mismatches
=> fix signature for alpaca.data.live.crypto.CryptoDataStream.subscribe_bars

alpaca/broker/enums.py
Context:
- options/custodial_customer agreements are added in the API
- https://docs.alpaca.markets/reference/createaccount
Changes:
- add options_agreement
- add custodial_customer_agreement
=> feat: Add options/custodial_customer agreements

alpaca/common/exceptions.py
Given that the APIError object returns both a code and message, both should be readily accessible to the end user. The end user can already access this by accessing the protected variable _error, but that isn't best practice.
This would address #431
=> Added message property to APIError

alpaca/broker/client.py, alpaca/broker/models/documents.py, alpaca/broker/requests.py, alpaca/common/requests.py, tests/broker/broker_client/test_documents_routes.py
Context:
- UploadW8BenDocumentRequest is not used in the code path
Change:
- add UploadW8BenDocumentRequest into accepting type for:
- create_account
- upload_documents_to_account
=> feat: Support w8ben

alpaca/data/live/websocket.py, alpaca/trading/stream.py
Context:
- websockets 14 changes import paths for deprecated functions
- https://websockets.readthedocs.io/en/stable/project/changelog.html#id4
- according to upgrade guide, we can use `websockets.legacy.client.connect()` instead of `websockets.connect()` for a while
- https://websockets.readthedocs.io/en/stable/howto/upgrade.html#import-paths
Changes:
- use `websockets.legacy.client.connect()`
=> fix: Support websockets 14

alpaca/trading/client.py, alpaca/trading/requests.py
fixes https://github.com/alpacahq/alpaca-py/issues/533
Context:
- get_portfolio_history is not implemented in TradingClient
Changes:
- add get_portfolio_history for TradingClient
=> feat: Support get_portfolio_history for TradingClient

examples/crypto-trading-basic.ipynb
A hotfix for #537 by changing the symbol string before and after managing positions in the crypto demo.
=> #537 (Crypto demo APIError) Hotfix

alpaca/trading/models.py, tests/broker/broker_client/test_trading_routes.py, tests/common/factories/trading.py, tests/common/test_common_models.py, tests/trading/trading_client/test_order_routes.py, tests/trading/trading_client/test_position_routes.py
Closes https://github.com/alpacahq/alpaca-py/issues/539
Context:
- position_intent is missing in order object
Changes:
- add position_intent into order object
=> feat: Add position_intent into order model

alpaca/trading/enums.py
I noticed the websocket returning the string "pending_new" for TradeEvent and had to hard code around it being missing from `TradeEvent`
=> feat: add PENDING_NEW trade event to TradeEvent enum

alpaca/trading/models.py, tests/trading/trading_client/test_order_routes.py
Context:
- merged a PR to add position_intent into order model
- https://github.com/alpacahq/alpaca-py/pull/540
- position_intent is empty for orders before introducing it
- Therefore, it should be optional
Changes:
- set position_intent optional
=> fix: Set position_intent optional

examples/crypto-trading-basic.ipynb, examples/options-trading-basic.ipynb, examples/stocks-trading-basic.ipynb
Fixes https://github.com/alpacahq/alpaca-py/issues/549 by calling the pip install command only when importing fails.
=> fix: In-notebook install command no longer triggered if `alpaca` already importable

alpaca/trading/models.py
The `get_portfolio_history` API returns an optional `cashflow` property, which is a mapping of activity type to cash flow amounts.
=> fix: Add cashflow property to PortfolioHistory model

alpaca/trading/models.py
Context:
- `TradingStream.subscribe_trade_updates()` causes a validation error for MLeg(multi-leg) orders
- position_intent of order in trade_updates is empty string ("")
```
ERROR:alpaca.trading.stream:error during websocket communication: 1 validation error for TradeUpdate
order.position_intent
Input should be 'buy_to_open', 'buy_to_close', 'sell_to_open' or 'sell_to_close' [type=enum, input_value='', input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/enum
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/alpaca/trading/stream.py", line 173, in _run_forever
await self._consume()
File "/usr/local/lib/python3.11/dist-packages/alpaca/trading/stream.py", line 146, in _consume
await self._dispatch(msg)
File …
```
=> fix: Fix position_intent for mleg order

alpaca/trading/models.py
Context:
- expires_at is introduced in [Aged order policy](https://docs.alpaca.markets/docs/orders-at-alpaca#aged-order-policy)
Changes:
- add expires_at into Order
=> feat: Add expires_at into Order

.github/workflows/stale.yml
Context:
- add [stale github actions](https://github.com/actions/stale)
- current setup is only for PR
- stale: 30 days of no activity
- close: 5 days after stale with no activity
- issue is out of scope (currently)
Changes:
- add stale github actions
=> chore: Add stale github actions

alpaca/data/historical/option.py
Fixes incorrect docstring in `get_option_latest_trade()`:
- Changed `OptionLatestQuoteRequest` to `OptionLatestTradeRequest`
- Updated return type from `Union[Dict[str, Quote], RawData]` to `Union[Dict[str, Trade], RawData]`
This corrects the documentation to match the actual function behavior.
=> fix: Incorrect documentation for get_option_latest_trade

.github/workflows/stale.yml
Context:
- added stale github actions
- https://github.com/alpacahq/alpaca-py/pull/562
- required permission is missing and had an error
- `[#324] Error when adding a label: Resource not accessible by integration`
- ref. https://github.com/actions/stale?tab=readme-ov-file#stale-pr-label
- ref. https://github.com/actions/stale?tab=readme-ov-file#close-pr-message
- ref. https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions
Changes:
- add pr write permission to stale github actions job
=> fix: Add pr write permission to stale

alpaca/broker/enums.py
In fact, Alpaca server returns transfer status "SETTLED", at least from transfer events SSE endpoint, e.g.
```
data: {"status_to": "CANCELED", "status_from": "SETTLED", "transfer_id": "bf438b6d-4ea3-4241-9e1c-a0e55b47f4e0", "account_id": "2d6cab28-c5d1-4ff8-91c6-b6404a9ee114", "at": "2024-07-22T08:22:29.990176Z", "event_ulid": "01J3CRHXB6ZHG4K120EWYQDB5X"}
```
=> Add `SETTLED` to `TransferStatus` enum

alpaca/trading/client.py
Context:
- The docstring of `TradingClient.cancel_order_by_id()` mentioned `CancelOrderResponse` as response
- However, the TradingClient.cancel_order_by_id() returns `None` currently.
- The docstring should be aligned with actual behaviour of TradingClient.cancel_order_by_id()
Changes:
- adjust docstring `Retruns` to None for TradingClient.cancel_order_by_id()
=> fix: Adjust docstring of TradingClient.cancel_order_by_id()

alpaca/common/rest.py
Reverts alpacahq/alpaca-py#578
=> introduced an issue of `alpaca.common.exceptions.APIError: {"message":"unexpected query parameter(s): limit"}` for some marketdata API endpoints. mainly for `/latest` and `/snapshots`
I have tried to fix to filter those endpoints but seems it might take sometime. so, revert the change first then later considering proper way
fixes https://github.com/alpacahq/alpaca-py/issues/581
=> fix: Revert "Use 10 000 as the default page limit for marketdata queries"

alpaca/data/enums.py
closes https://github.com/alpacahq/alpaca-py/issues/571
Context:
- The latest data API endpoints of MarketData API support delayed_sip for feed parameter
Changes:
- add DELAYED_SIP for DataFeed enum
=> feat: Add DELAYED_SIP for DataFeed

alpaca/trading/models.py, tests/broker/broker_client/test_trading_routes.py
fixes https://github.com/alpacahq/alpaca-py/issues/596
Context:
- PortfolioHistory.base_value encountered validation error is reported
```
1 validation error for PortfolioHistory
base_value
Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
```
Changes:
- change PortfolioHistory.base_value to Optional[float]
=> fix: Change PortfolioHistory.base_value to Optional[float]

alpaca/data/enums.py
Context:
- overnight related datafeed is added for MarketData API
- ref. https://docs.alpaca.markets/reference/stocklatestbars-1
Changes:
- add `OVERNIGHT` and `BOATS` DataFeed enum values
=> feat: Add DataFeed for overnight trading

alpaca/data/historical/corporate_actions.py, alpaca/data/models/corporate_actions.py, alpaca/data/requests.py, tests/data/test_corporate_actions.py
closes https://github.com/alpacahq/alpaca-py/issues/584
Context:
- corporate actions response object now has id/cusip
Changes:
- support id/cusip for corporate actions
=> feat: Support ID/CUSIPs of corporate action

alpaca/trading/client.py, tests/trading/trading_client/test_corporate_announcements.py
Context:
- corporate actions endpoints of Trading API are deprecated
- https://docs.alpaca.markets/reference/get-v2-corporate_actions-announcements-1
- https://docs.alpaca.markets/reference/get-v2-corporate_actions-announcements-id-1
- There is a new corporate actions endpoint in Market Data API
- https://docs.alpaca.markets/reference/corporateactions-1
Changes:
- deprecate alpaca.trading.TradingClient.get_corporate_announcements()
=> docs: Deprecate get_corporate_announcements

alpaca/trading/enums.py
https://github.com/alpacahq/alpaca-py/issues/624
Here are a few options on how to proceed, based on your judgement. 
1. If the issue is due to Alpaca adding a new AssetClass type and AssetExchange type, then we should merge this PR. 
2. However, if this is a data corruption issue, then we don't need to proceed with this PR. 
For folks experiencing the same issue, you can temporarily change your alpaca-py dependency from
```
pip install alpaca-py
```
to
```
pip install git+https://github.com/yushdotkapoor/alpaca-py.git
```
The steps that were failing in the [Issue](https://github.com/alpacahq/alpaca-py/issues/624) are now passing
```
from alpaca.trading.client import TradingClient
alpaca = TradingClient(api_key={api_key}, secret_key={secret_key}, paper={is_mock})
alpaca.get_all_assets() …
```
=> fix: Add new asset classes for perpetual crypto and ASCX exchange
