alpacahq/alpaca-py

alpaca/common/models/__init__.py, alpaca/common/models/calendar.py, tests/common/test_common_models.py
=> Adds Calendar Model

alpaca/broker/client.py, alpaca/broker/models/requests.py, tests/broker/broker_client/test_misc_routes.py
=> Broker API: Clock & Calendar

CONTRIBUTING.md
=> Adds in an initial CONTRIBUTING file 

alpaca/broker/client.py, alpaca/broker/enums.py, alpaca/broker/models/__init__.py, alpaca/broker/models/journals.py, alpaca/broker/models/requests.py, tests/broker/broker_client/test_journal_routes.py, tests/broker/factories/__init__.py, tests/broker/factories/journals.py, tests/broker/test_models.py
=> Broker API: Journals

alpaca/broker/client.py, alpaca/common/models/requests.py, alpaca/trading/client.py, alpaca/trading/models/requests.py, tests/trading/test_trading_models.py, tests/trading/trading_client/test_asset_routes.py
=> Broker API: Assets

alpaca/broker/client.py, alpaca/broker/enums.py, alpaca/broker/models/accounts.py, alpaca/broker/models/requests.py, alpaca/common/enums.py, alpaca/common/models/accounts.py, alpaca/trading/client.py, tests/trading/trading_client/test_account_routes.py
=> Trading API: Account

alpaca/common/models/requests.py, alpaca/trading/client.py
=> Trading API: Watchlists

docs/_templates/base.html
[Jira Ticket ](https://alpaca.atlassian.net/browse/ENG-12214)
Extends base template to add script to <head> tag that is used on every page
=> ENG-12214 add GA to base template of theme

alpaca/common/enums.py
=> Adds Crypto Exchanges to AssetExchange 

docs/_templates/base.html
Adds Amplitude event tracking to each page. 
On page load an event is fired - "<formatted_url_path>_page_visited"
When a search is submitted thru the search input an event is fired "docs_alpaca_sdk_search" with the search_input as an event parameter.
=> ENG-13041: Add Amplitude to Alpaca-Py

alpaca/broker/client.py, alpaca/trading/client.py
Fixes [this issue](https://github.com/alpacahq/alpaca-py/issues/148)
=> Fix: using isinstance to check list type

alpaca/common/exceptions.py
Fix for https://github.com/alpacahq/alpaca-py/issues/166
=> bug fix -- fix for accessing APIError.code throws TypeError

README.md
Add update instructions in the readme file
=> [Docs] Add update instructions

README.md, docs/broker.rst
=> Fix: typos

alpaca/data/enums.py, alpaca/data/historical/screener.py, alpaca/data/models/screener.py, alpaca/data/requests.py, tests/conftest.py, tests/data/test_screener.py
Added support for screener endpoints https://docs.alpaca.markets/reference/mostactives & https://docs.alpaca.markets/reference/movers
=> Screener endpoints

alpaca/broker/requests.py, poetry.lock, pyproject.toml
Update websocket and websockets versions.
=> Bump websockets to v11

alpaca/broker/requests.py, alpaca/common/websocket.py, alpaca/data/historical/crypto.py, alpaca/data/historical/stock.py, alpaca/data/requests.py, alpaca/trading/enums.py, alpaca/trading/requests.py, tests/broker/broker_client/test_journal_routes.py, tests/broker/factories/journals.py, tests/broker/test_models.py, tests/data/test_historical_crypto_data.py, tests/data/test_historical_stock_data.py, tests/data/test_websockets.py, tests/trading/trading_client/test_order_routes.py
This allows the SDK to choose what assets an account should have when opening an account.
=> adding optional enabled assets e.g. you don't want to enable crypto

alpaca/data/requests.py
- would like to add sort parameter into [the docs](https://alpaca.markets/docs/python-sdk/api_reference/data/stock/requests.html#alpaca.data.requests.StockBarsRequest)
=> feat: Add sort parameter into docstring

README.md
- update links to the alpaca-py docs in README.md
=> fix: Update links to docs

alpaca/trading/models.py, alpaca/trading/requests.py, tests/trading/trading_client/test_asset_routes.py
Context:
- we missed attributes parameter for GetAssetsRequest
Changes:
- add attributes parameter for GetAssetsRequest
=> feat: Support asset attributes filter for get_all_assets()

alpaca/trading/client.py, alpaca/trading/enums.py, alpaca/trading/models.py, alpaca/trading/requests.py, tests/trading/trading_client/test_option_routes.py
Context:
- a new api endpoint, options/contracts are introduced
Changes:
- support options contracts api endpoint
=> feat: Add get option contracts

alpaca/common/enums.py, alpaca/data/live/option.py
Context:
- option stream data is introduced
Changes:
- add OptionDataStream
=> feat: Support option stream data

README.md, docs/api_reference/data/option.rst, docs/api_reference/data/option/historical.rst, docs/api_reference/data/option/live.rst, docs/api_reference/data/option/requests.rst, docs/api_reference/data_api.rst, docs/api_reference/trading/contracts.rst, docs/api_reference/trading_api.rst, docs/getting_started.rst, docs/index.rst, docs/market_data.rst, examples/options-trading-basic.ipynb
- update docs for options trading
=> doc: Update docs for options trading

alpaca/trading/models.py, examples/options-trading-basic.ipynb, tests/trading/trading_client/test_account_routes.py
Context:
- options related field names are renamed
Changes:
- rename options related fields
=> feat: Rename options fields

alpaca/common/websocket.py, alpaca/data/enums.py, alpaca/data/live/option.py, alpaca/data/requests.py, tests/data/test_historical_option_data.py
Context:
- feed parameter is added for options data api endpoint
Changes:
- support feed parameter for options data api endpoint
=> feat: Support OptionsFeed

alpaca/broker/enums.py
We have an error of validation due to lacking of Alpaca_APCA
=> fix: Add Alpaca_APCA ClearingBroker

alpaca/broker/models/accounts.py
=> Update Agreement model in accounts

README.md
closes https://github.com/alpacahq/alpaca-py/issues/399
- doc enhancement 
- introduce other HistoricalDataClient in README.md
=> doc: Update README.md to introduce stock/options historical data client

alpaca/data/models/news.py, tests/conftest.py, tests/data/test_historical_news_data.py
Context:
- an error happens when fetching historical news data
Changes:
- fix fetching historical news
=> fix: Fix historical news data

alpaca/broker/models/journals.py
Context:
- we have an issue of fetching a journal
Changes:
- add optional to currency of Journal model
=> fix: Add optional to currency of Journal model

docs/api_reference/trading/requests.rst
Context:
- noticed that OptionLegRequest is missing in API reference doc
Changes:
- add OptionLegRequest into doc
=> fix: Add OptionLegRequest into requests.rst

docs/market_data.rst
closes https://github.com/alpacahq/alpaca-py/issues/575
Context:
- sample import code should include `.live` for stream client
Changes:
- use alpaca.data.live
=> fix: Adjust real time data example code

CONTRIBUTING.md, docs/market_data.rst
Change:
- Update minor typos in market data and contribution docs
=> fix: Update docs typos

alpaca/broker/requests.py, tests/broker/test_models.py
Fix issue https://github.com/alpacahq/alpaca-py/issues/605
=> FIX: activity_types field serialization in GetAccountActivitiesRequest
